name: RyanAirRun

on:
  workflow_dispatch:
    inputs:
      root_origin_code:
      start_within_days:
      min_stay_hours:
      max_stay_hours:
      max_away_days:
      country_whitelist:
      max_routes:
      sleep:

env:
  mailto: ${{ secrets.MAILTO }}
  PYTHONUNBUFFERED: true

jobs:
  all:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - run: > 
        python ryanair.py
        --root_origin_code ${{ github.event.inputs.root_origin_code }}
        --start_within_days ${{ github.event.inputs.start_within_days }}
        --max_away_days ${{ github.event.inputs.max_away_days }}
        --country_whitelist ${{ github.event.inputs.country_whitelist }}
        --max_routes ${{ github.event.inputs.max_routes }}
        --sleep ${{ github.event.inputs.sleep }}
        --no_tqdm
