name: RyanAirRun

on:
  workflow_dispatch:
    inputs:
      root_origin:
      start_within:
      min_stay:
      max_away:


jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - run: > 
        python ryanair.py
        --root_origin ${{ github.event.inputs.root_origin }}
        --start_within ${{ github.event.inputs.start_within }}
        --min_stay ${{ github.event.inputs.min_stay }}
        --max_away ${{ github.event.inputs.max_away }}
