name: RyanAirRun

on:
  workflow_dispatch:
    inputs:
      root_origin_code:
      start_not_before:
      start_until:
      max_away_days:
      min_stay_days:
      country_whitelist:
      blacklist:
      max_routes:
      via:
      sleep:

env:
  mailto: ${{ secrets.MAILTO }}
  PYTHONUNBUFFERED: true

jobs:
  all:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - run: > 
        python ryanair.py
        --root_origin_code ${{ github.event.inputs.root_origin_code }}
        --start_not_before ${{ github.event.inputs.start_not_before }}
        --start_until ${{ github.event.inputs.start_until }}
        --max_away_days ${{ github.event.inputs.max_away_days }}
        --min_stay_days ${{ github.event.inputs.min_stay_days }}
        --country_whitelist ${{ github.event.inputs.country_whitelist }}
        --blacklist ${{ github.event.inputs.blacklist }}
        --max_routes ${{ github.event.inputs.max_routes }}
        --via ${{ github.event.inputs.via }}
        --sleep ${{ github.event.inputs.sleep }}
